# Generated by Django 5.0.7 on 2024-11-30 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.TextField(blank=True, db_column='Recipe', null=True)),
                ('mealtype', models.TextField(blank=True, db_column='MealType', null=True)),
            ],
            options={
                'db_table': 'meals',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PregnancyDietaryNeeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.TextField(blank=True, db_column='Recipe', null=True)),
                ('cuisine', models.TextField(blank=True, db_column='Cuisine', null=True)),
                ('calories', models.IntegerField(blank=True, db_column='Calories', null=True)),
                ('protein', models.FloatField(blank=True, db_column='Protein', null=True)),
                ('vitamin_b9', models.IntegerField(blank=True, db_column='Vitamin_B9', null=True)),
                ('vitamin_d', models.IntegerField(blank=True, db_column='Vitamin_D', null=True)),
                ('vitamin_a', models.IntegerField(blank=True, db_column='Vitamin_A', null=True)),
                ('iron', models.FloatField(blank=True, db_column='Iron', null=True)),
                ('calcium', models.IntegerField(blank=True, db_column='Calcium', null=True)),
                ('omega_3', models.FloatField(blank=True, db_column='Omega_3', null=True)),
                ('iodine', models.IntegerField(blank=True, db_column='Iodine', null=True)),
                ('trimester', models.TextField(blank=True, db_column='Trimester', null=True)),
                ('genetic_condition', models.TextField(blank=True, db_column='Genetic_Condition', null=True)),
                ('allergy', models.TextField(blank=True, db_column='Allergy', null=True)),
                ('food_habit', models.TextField(blank=True, db_column='Food_Habit', null=True)),
                ('activity_level', models.TextField(blank=True, db_column='Activity_Level', null=True)),
                ('age', models.IntegerField(blank=True, db_column='Age', null=True)),
                ('height', models.IntegerField(blank=True, db_column='Height', null=True)),
                ('weight', models.IntegerField(blank=True, db_column='Weight', null=True)),
                ('ingredients', models.TextField(blank=True, db_column='Ingredients', null=True)),
            ],
            options={
                'db_table': 'pregnancy_dietary_needs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(choices=[('18-25', '18-25'), ('26-35', '26-35'), ('36-45', '36-45'), ('46+', '46+')], max_length=50)),
                ('trimester', models.CharField(choices=[('1', 'First'), ('2', 'Second'), ('3', 'Third')], max_length=10)),
                ('allergy', models.CharField(blank=True, choices=[('none', 'None'), ('nuts', 'Nuts'), ('dairy', 'Dairy'), ('gluten', 'Gluten'), ('shellfish', 'Shellfish'), ('other', 'Other')], max_length=100, null=True)),
                ('genetic_condition', models.CharField(blank=True, choices=[('none', 'None'), ('diabetes', 'Diabetes'), ('hypertension', 'Hypertension'), ('heart-disease', 'Heart Disease'), ('other', 'Other')], max_length=100, null=True)),
                ('food_habits', models.CharField(choices=[('vegetarian', 'Vegetarian'), ('non-vegetarian', 'Non-Vegetarian'), ('vegan', 'Vegan'), ('pescatarian', 'Pescatarian'), ('other', 'Other')], max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
