# Generated by Django 5.0.7 on 2025-03-26 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan1', '0002_mealplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='allergy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='genetic_condition',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
