# Generated by Django 5.0.7 on 2025-03-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan1', '0003_alter_profile_allergy_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meals',
            options={},
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='allergy',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='food_habits',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='genetic_condition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='trimester',
            field=models.CharField(max_length=10),
        ),
    ]
