# Generated by Django 5.0.7 on 2025-03-28 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodplan1', '0004_alter_meals_options_alter_profile_age_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meals',
            options={'managed': False},
        ),
    ]
